version: "3"
services:

  app:
    build: .
    ports: 
      - "8000:8000"
    volumes: 
      - .:/home/
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3307:3306"
    environment:
      MYSQL_DATABASE: webstore
      MYSQL_USER: mateus
      MYSQL_ROOT_PASSWORD: teste1

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    links: 
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1